### ISSUE TITLE
Ped not crouching properly

### ISSUE THREAD

**Issue by ItzTrivialOld** [BaziForYou/Enhanced_Crouch#3]
The ped is sadly not crouching properly on my end. After just about half a second it resets the animation and the ped walks normally again. It doesnt matter if the ped is standing still or walking. I checked for any other command called crouch or Keymapping or any other value related to the ones the crouch script uses. 

I hope you can help me with my problem. Thanks up front.

**Comment by kloudzx** [comment]
also having this issue since latest updates.
when i hit c to recenter my camera it would stop you from crouching.
